// apps/inventar-next/src/app/funk/page.tsx
'use client';

import { Tabs } from '@/components/base';
import AddDevice from '@/components/scan/AddDevice';
import { useFunkStore } from '@/provider/store/funkStore';
import { useParams, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';

type FunkTab = 'Funkgeräte' | 'Ausleihhistorie' | 'Erweitert';

export default function FunkPage() {
  const [selectedTab, setSelectedTab] = useState<FunkTab>('Funkgeräte');
  const params = useParams();
  const router = useRouter();

  const { funkItems, funkItemEventBulks } = useFunkStore();
  console.log('funkItems', funkItems);
  console.log('funkItemEventBulks', funkItemEventBulks);

  useEffect(() => {
    const tab = params.tab;
    if (tab) {
      setSelectedTab(tab as FunkTab);
    }
  }, [params.tab]);

  return (
    <div className="flex flex-col gap-4 p-4">
      <AddDevice
        reset={() => {
          console.log('reset');
        }}
      />

      <div className="flex w-full justify-center">
        <Tabs
          initialSelected={selectedTab}
          items={['Funkgeräte', 'Ausleihhistorie', 'Erweitert'] satisfies FunkTab[]}
          onSelect={(item) => {
            setSelectedTab(item as FunkTab);
            router.push(`/funk?tab=${item}`);
          }}
        />
      </div>
      {funkItems && funkItemEventBulks && (
        <>
          {funkItems.map((item) => (
            <div key={item.id}>{item.deviceId}</div>
          ))}
          {funkItemEventBulks.map((bulk) => (
            <div key={bulk.id}>{bulk.id}</div>
          ))}
        </>
      )}
      {/* 
{#await $funk.fetching}
    <LoadingSpinner />
{:then}
    {#if selectedTab === 'bulkHistory'}
        <FunkBulkHistoryTab />
    {:else if selectedTab === 'advanced'}
        <FunkAdvancedTab />
    {:else}
        <FunkListTab />
    {/if}
{:catch error}
    <ErrorState
        label="Beim Abrufen der Funkgeräte aus der Datenbank ist leider ein Fehler aufgetreten."
        {error}
    />
{/await} */}
    </div>
  );
}

// apps/inventar/src/routes/(main)/(funk)/funk/+page.svelte
<script lang="ts">
	import { goto, invalidateAll } from '$app/navigation';
	import { page } from '$app/stores';
	import ErrorState from '$lib/ErrorDisplay.svelte';
	import { LoadingSpinner } from '@thw-tools/svelte-components';
	import { Tabs } from '@thw-tools/svelte-components';
	import AddDevice from '$lib/funk/AddDevice.svelte';
	import FunkAdvancedTab from '$lib/funk/FunkAdvancedTab.svelte';
	import FunkBulkHistoryTab from '$lib/funk/FunkBulkHistoryTab.svelte';
	import FunkListTab from '$lib/funk/FunkListTab.svelte';
	import { funk } from '$lib/shared/stores/funkStore';
	import { onDestroy, onMount } from 'svelte';

	const tabs = {
		funkList: 'Funkgeräte',
		bulkHistory: 'Ausleihhistorie',
		advanced: 'Erweitert'
	} as const;

	type FunkTab = keyof typeof tabs;
	type FunkTabValue = (typeof tabs)[FunkTab];

	let selectedTab: FunkTab = $state('funkList');
	let lastHiddenTime: number | null = null;

	const invalidationThreshold = 2 * 60 * 1000; // 2 minutes

	function handleVisibilityChange() {
		if (document.hidden && !lastHiddenTime) {
			lastHiddenTime = Date.now();
			return;
		}

		if (!document.hidden && lastHiddenTime) {
			const timeElapsed = Date.now() - lastHiddenTime;
			if (timeElapsed > invalidationThreshold) {
				console.log('Invalidating data due to tab being hidden for too long');

				// Invalidate data if the tab was hidden for too long
				invalidateAll();
				lastHiddenTime = null;
			}
			return;
		}
	}

	const isBrowser = typeof window !== 'undefined';

	onMount(() => {
		if (!isBrowser) return;

		const tab = $page.url.searchParams.get('tab');
		if (tab) {
			selectedTab = tab as FunkTab;
		}

		document.addEventListener('visibilitychange', handleVisibilityChange);
	});

	onDestroy(() => {
		if (!isBrowser) return;

		document.removeEventListener('visibilitychange', handleVisibilityChange);
	});

	const onTabSelect = (selected: FunkTab) => {
		selectedTab = selected;

		if (selectedTab === 'funkList') {
			$page.url.searchParams.delete('tab');
		} else {
			$page.url.searchParams.set('tab', selected);
		}
		goto(`?${$page.url.searchParams.toString()}`);
	};
</script>

<div class="flex flex-col gap-4 p-4">
	<AddDevice reset={invalidateAll} />

	<div class="flex w-full justify-center">
		<Tabs
			items={Object.entries(tabs).map(([key, value]) => ({
				key: key as FunkTab,
				label: value as FunkTabValue
			}))}
			onSelect={onTabSelect}
			initialSelected={($page.url.searchParams.get('tab') as FunkTab) ?? undefined}
		/>
	</div>

	{#await $funk.fetching}
		<LoadingSpinner />
	{:then}
		{#if selectedTab === 'bulkHistory'}
			<FunkBulkHistoryTab />
		{:else if selectedTab === 'advanced'}
			<FunkAdvancedTab />
		{:else}
			<FunkListTab />
		{/if}
	{:catch error}
		<ErrorState
			label="Beim Abrufen der Funkgeräte aus der Datenbank ist leider ein Fehler aufgetreten."
			{error}
		/>
	{/await}
</div>
