// apps/inventar/src/lib/FloatingActionButton.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { trackEvent } from './utils';
	import { fade } from 'svelte/transition';

	interface Props {
		click?: (() => void) | undefined;
		dataUmamiEvent?: string | undefined;
		children?: import('svelte').Snippet;
		visible?: boolean;
	}

	let { click, dataUmamiEvent = undefined, children, visible = true }: Props = $props();

	let mounted = $state(false);

	onMount(() => {
		mounted = true;
	});
</script>

{#if visible && mounted}
	<button
		transition:fade={{ duration: 200 }}
		class="md:hidden fixed bottom-4 right-4 bg-thw text-white border-2 border-white hover:bg-thw-900 rounded-full h-16 w-16 p-4 z-50 flex items-center justify-center"
		onclick={async () => {
			if (click) click();
			trackEvent(dataUmamiEvent);
		}}
	>
		{@render children?.()}
	</button>
{/if}

// apps/inventar-next/src/components/scan/FloatingActionButton.tsx
'use client';

import { Button } from '@/components/base';

interface Props {
  onClick: () => void;
  visible: boolean;
  children: React.ReactNode;
}

export default function FloatingActionButton({ onClick, visible, children }: Props) {
  if (!visible) return null;

  return (
    <div className="fixed bottom-6 right-6 z-50">
      <Button
        type="primary"
        size="large"
        onClick={onClick}
        className="rounded-full w-14 h-14 flex items-center justify-center shadow-lg hover:shadow-xl transition-shadow"
      >
        {children}
      </Button>
    </div>
  );
}
