// src/lib/inventar/InventarItemEventTypeBadge.svelte
<script lang="ts">
	import { eventTypeToFriendlyString, type InventarItemEventType } from '../api/inventarItem';

	export let type: InventarItemEventType;
</script>

<div class="rounded-xl text-sm px-2 h-min bg-green-200" class:isBorrowed={type === 'borrowed'}>
	{eventTypeToFriendlyString(type)}
</div>

<style lang="scss">
	.isBorrowed {
		@apply bg-red-200;
	}
</style>

// apps/inventar-next/src/components/scan/InventarItemEventTypeBadge.tsx
import { eventTypeToFriendlyString, FunkItemEventType } from '@/api/funk/funkModels';
import { cn } from '@/lib/utils';

export default function InventarItemEventTypeBadge({ type }: { type: FunkItemEventType }) {
  return (
    <div
      className={cn(
        'rounded-xl text-sm px-2 h-min bg-green-200',
        type === 'borrowed' && 'bg-red-200'
      )}
    >
      {eventTypeToFriendlyString(type)}
    </div>
  );
}
