// apps/inventar-next/src/components/scan/AddDevice.tsx
import {
  FunkItemDeviceId,
  FunkItemDeviceIdSchema,
  FunkItemEvent,
  FunkItemEventType,
} from '@/api/funk/funkModels';
import QRScanner from './QRScanner';
import { toast } from 'sonner';
import { useCallback, useState } from 'react';
import { useFunkStore } from '@/provider/store/funkStore';
import { Button } from '../base';
import Input from '../base/Input';
import { useKindeAuth } from '@kinde-oss/kinde-auth-react';
import { ApiRequestOptions } from '@/api/apiGeneric';
import { batteryCountToFriendlyString, eventTypeToFriendlyString } from '@/api/funk/funkModels';
import ManuelDeviceIdInput from './ManuelDeviceIdInput';

interface Props {
  reset: () => void;
}

export default function AddDevice({ reset }: Props) {
  const { getAccessToken, getIdToken } = useKindeAuth();

  const [scannedDeviceIds, setScannedDeviceIds] = useState<
    {
      deviceId: FunkItemDeviceId;
      lastEvent?: FunkItemEvent;
    }[]
  >([]);
  const [batteryCountInput, setBatteryCountInput] = useState<string>('0');

  const {
    getFunkItemByDeviceId,
    getLastFunkItemEventByFunkItemInternalId,
    bulkCreateFunkItemEvents,
  } = useFunkStore();

  const onScan = useCallback(
    (decodedText: string, isQrScan: boolean = false) => {
      if (!decodedText) {
        return;
      }

      const parsed = FunkItemDeviceIdSchema.safeParse(decodedText.trim());

      if (!parsed.success) {
        toast.error(`Ungültige Geräte-ID: ${decodedText}`);
        return;
      }

      // Use functional update to access current state
      setScannedDeviceIds((currentScannedDeviceIds) => {
        if (currentScannedDeviceIds.some((item) => item.deviceId === decodedText)) {
          return currentScannedDeviceIds; // Return unchanged state if device already exists
        }

        const existingItem = getFunkItemByDeviceId(parsed.data);
        const lastEvent = existingItem && getLastFunkItemEventByFunkItemInternalId(existingItem.id);

        const newState = [
          ...currentScannedDeviceIds,
          {
            deviceId: parsed.data,
            lastEvent,
          },
        ];

        if (isQrScan) {
          // playScanSound();
        }

        toast.success(`Gerät mit der ID ${parsed.data} gescannt.`);

        return newState;
      });
    },
    [getFunkItemByDeviceId, getLastFunkItemEventByFunkItemInternalId]
  );

  const submit = async (eventType: FunkItemEventType) => {
    if (scannedDeviceIds.length == 0) {
      return;
    }

    const batteryCount = parseInt(batteryCountInput);

    const accessToken = await getAccessToken();
    const idToken = await getIdToken();
    if (!accessToken || !idToken) {
      return;
    }

    const requestOptions: ApiRequestOptions = {
      token: accessToken,
      idToken,
    };

    await bulkCreateFunkItemEvents(
      requestOptions,
      scannedDeviceIds.map((e) => e.deviceId),
      batteryCount,
      eventType
    );

    toast.success(
      `${scannedDeviceIds.length} Gerät${scannedDeviceIds.length > 1 ? 'e' : ''} und ${batteryCountToFriendlyString(batteryCount)} wurden erfolgreich ${eventTypeToFriendlyString(eventType)}.`
    );

    setScannedDeviceIds([]);
    reset();
  };

  return (
    <div>
      <div className="flex flex-col gap-2">
        <QRScanner onScan={onScan} />
        <ManuelDeviceIdInput onScan={onScan} />
      </div>
      {scannedDeviceIds.length > 0 && (
        <div className="flex flex-col gap-2">
          <div className="font-bold text-2xl">Gescannte Geräte:</div>
          <div>
            {scannedDeviceIds.map((scannedDeviceId) => (
              <div key={scannedDeviceId.deviceId} className="flex gap-2 items-center">
                <div>{scannedDeviceId.deviceId}</div>
                {scannedDeviceId.lastEvent && (
                  // <InventarItemEventTypeBadge type={scannedDeviceId.lastEvent.type} />
                  <div>{scannedDeviceId.lastEvent.type}</div>
                )}
              </div>
            ))}
          </div>

          <Input
            label="Batterien"
            type="number"
            placeholder="Anzahl Batterien"
            value={batteryCountInput}
            onChange={setBatteryCountInput}
            inputMode="numeric"
          />

          <div className="flex gap-2 w-full justify-between">
            <Button
              type={
                scannedDeviceIds.every(
                  (scannedDeviceId) => scannedDeviceId.lastEvent?.type === 'returned'
                )
                  ? 'secondary'
                  : 'primary'
              }
              onClick={() => submit('returned')}
            >
              Zurückgeben
            </Button>
            <Button
              type={
                scannedDeviceIds.every(
                  (scannedDeviceId) => scannedDeviceId.lastEvent?.type === 'borrowed'
                )
                  ? 'secondary'
                  : 'primary'
              }
              onClick={() => submit('borrowed')}
            >
              Ausleihen
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

// src/lib/inventar/AddDevice.svelte
<script lang="ts">
	import { bulkCreateInventarItemEvents } from '$lib/api/inventarApi';
	import Button from '$lib/Button.svelte';
	import Input from '$lib/Input.svelte';
	import ManuelDeviceIdInput from '$lib/inventar/ManuelDeviceIdInput.svelte';
	import QrScanner from '$lib/inventar/QRScanner.svelte';
	import { bannerMessage } from '$lib/shared/stores/bannerMessage';
	import {
		batteryCountToFriendlyString,
		eventTypeToFriendlyString,
		validateInventarItemDeviceId,
		type InventarItem,
		type InventarItemDeviceId,
		type InventarItemEventType
	} from './inventarItem';
	import InventarItemEventTypeBadge from './InventarItemEventTypeBadge.svelte';

	export let inventarItems: InventarItem[];
	export let reset: () => void;

	let scannedDeviceIds: {
		deviceId: InventarItemDeviceId;
		existingItem?: InventarItem;
	}[] = [];

	let batteryCountInput: string = '0';

	async function onScan(decodedText: string) {
		if (!decodedText) {
			return;
		}

		decodedText = decodedText.trim();

		if (!validateInventarItemDeviceId(decodedText)) {
			$bannerMessage = {
				message: `Ungültige Geräte-ID: ${decodedText}`,
				autoDismiss: {
					duration: 5 * 1000
				},
				type: 'error'
			};
			return;
		}

		if (scannedDeviceIds.some((item) => item.deviceId === decodedText)) {
			return;
		}

		console.log(
			`Gerät mit der ID ${decodedText} gescannt.`,
			inventarItems.find((item) => item.deviceId === decodedText)
		);

		scannedDeviceIds = scannedDeviceIds.concat({
			deviceId: decodedText,
			existingItem: inventarItems.find((item) => item.deviceId === decodedText)
		});

		$bannerMessage = {
			message: `Gerät mit der ID ${decodedText} gescannt.`,
			autoDismiss: {
				duration: 5 * 1000
			}
		};
	}

	async function submit(eventType: InventarItemEventType) {
		if (scannedDeviceIds.length == 0) {
			return;
		}

		const batteryCount = parseInt(batteryCountInput);

		await bulkCreateInventarItemEvents(
			scannedDeviceIds.map((e) => e.deviceId),
			batteryCount,
			eventType
		);

		$bannerMessage = {
			message: `${scannedDeviceIds.length} Gerät${
				scannedDeviceIds.length > 1 ? 'e' : ''
			} und ${batteryCountToFriendlyString(
				batteryCount
			)} wurden erfolgreich ${eventTypeToFriendlyString(eventType)}.`,
			autoDismiss: {
				duration: 5 * 1000
			}
		};

		scannedDeviceIds = [];
		reset();
	}
</script>

<div class="flex flex-col gap-2">
	<QrScanner {onScan} />
	<ManuelDeviceIdInput {onScan} />
</div>

{#if scannedDeviceIds.length > 0}
	<div class="font-bold text-2xl">Gescannte Geräte:</div>
	<div>
		{#each scannedDeviceIds as scannedDeviceId}
			<div class="flex gap-2">
				<div>{scannedDeviceId.deviceId}</div>
				{#if scannedDeviceId.existingItem}
					<InventarItemEventTypeBadge type={scannedDeviceId.existingItem.lastEvent.type} />
				{/if}
			</div>
		{/each}
	</div>

	<Input
		label="Batterien"
		type="number"
		placeholder="Anzahl Batterien"
		bind:inputValue={batteryCountInput}
		inputmode="numeric"
	/>

	<div class="flex gap-2 w-full justify-between">
		<Button
			secondary={scannedDeviceIds.every(
				(scannedDeviceId) => scannedDeviceId.existingItem?.lastEvent?.type === 'returned'
			)}
			click={() => submit('returned')}>Zurückgeben</Button
		>
		<Button
			secondary={scannedDeviceIds.every(
				(scannedDeviceId) => scannedDeviceId.existingItem?.lastEvent?.type === 'borrowed'
			)}
			click={() => submit('borrowed')}>Ausleihen</Button
		>
	</div>
	<!-- <ScanInventarItemResultDialog
		deviceId={scannedDeviceId.deviceId}
		lastEvent={inventarItems.find((item) => item.deviceId === scannedDeviceId?.deviceId)?.lastEvent}
		onSubmit={submit}
	/> -->
{/if}
