// apps/inventar-next/src/components/dialog/AddVehicleDialog.tsx
import { CreateVehicleDto, CreateVehicleDtoSchema } from '@/api/vehicle/vehicleModels';
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { Button, Dialog } from '../base';

type Props = {
  isOpen: boolean;
  isSubmitting: boolean;
  onClose: () => void;
  onSubmit: (data: CreateVehicleDto) => void;
  onError: (message: string) => void;
};

export default function AddVehicleDialog({
  isOpen,
  isSubmitting,
  onClose,
  onSubmit,
  onError,
}: Props) {
  const {
    register,
    reset,
    getValues,
    formState: { errors, isValid },
  } = useForm<CreateVehicleDto>({
    defaultValues: {
      canBeReserved: true,
    },
  });

  // Common THW vehicle types
  const vehicleTypes = ['MTW', 'MzKw', 'GKW', 'MLW', 'Kipper', 'Anhänger', 'Sonstige'];

  // Reset form when dialog closes
  useEffect(() => {
    if (!isOpen) {
      reset();
    }
  }, [isOpen, reset]);

  const handleFormSubmit = () => {
    const result = CreateVehicleDtoSchema.safeParse(getValues());
    if (!result.success) {
      onError(result.error.message);
      return;
    }

    console.log('data', result.data);
    onSubmit(result.data);
  };

  const handleClose = () => {
    onClose();
  };

  if (!isOpen) {
    return null;
  }

  return (
    <Dialog title="Neues Fahrzeug hinzufügen">
      <div slot="content">
        <form className="space-y-4">
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
              Name*
            </label>
            <input
              id="name"
              type="text"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
              {...register('name')}
              placeholder="z.B. MTW OV Stab"
              required
            />
            {errors.name && <span className="text-red-600 text-sm">{errors.name.message}</span>}
          </div>

          <div>
            <label htmlFor="licensePlate" className="block text-sm font-medium text-gray-700 mb-1">
              Kennzeichen*
            </label>
            <input
              id="licensePlate"
              type="text"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
              {...register('licensePlate')}
              placeholder="z.B. THW-12345"
              required
            />
            {errors.licensePlate && (
              <span className="text-red-600 text-sm">{errors.licensePlate.message}</span>
            )}
          </div>

          <div>
            <label htmlFor="vehicleType" className="block text-sm font-medium text-gray-700 mb-1">
              Fahrzeugtyp*
            </label>
            <select
              id="vehicleType"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
              {...register('vehicleType')}
              required
            >
              <option value="" disabled>
                Bitte auswählen
              </option>
              {vehicleTypes.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
            {errors.vehicleType && (
              <span className="text-red-600 text-sm">{errors.vehicleType.message}</span>
            )}
          </div>

          <div>
            <label htmlFor="radioCallName" className="block text-sm font-medium text-gray-700 mb-1">
              Funkrufname
            </label>
            <input
              id="radioCallName"
              type="text"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
              {...register('radioCallName')}
              placeholder="z.B. Heros 86/25"
              required
            />
            {errors.radioCallName && (
              <span className="text-red-600 text-sm">{errors.radioCallName.message}</span>
            )}
          </div>

          <div>
            <label htmlFor="unit" className="block text-sm font-medium text-gray-700 mb-1">
              Einheit/Bereich
            </label>
            <input
              id="unit"
              type="text"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
              {...register('unit')}
              placeholder="z.B. OV Stab"
              required
            />
            {errors.unit && <span className="text-red-600 text-sm">{errors.unit.message}</span>}
          </div>

          <div>
            <label htmlFor="canBeReserved" className="flex items-center">
              <input
                id="canBeReserved"
                type="checkbox"
                className="mr-2 h-4 w-4 text-thw-500 focus:ring-thw-500 border-gray-300 rounded"
                {...register('canBeReserved')}
              />
              <span className="text-sm font-medium text-gray-700">Kann reserviert werden</span>
            </label>
            {errors.canBeReserved && (
              <span className="text-red-600 text-sm">{errors.canBeReserved.message}</span>
            )}
          </div>
        </form>
      </div>
      <div slot="footer">
        <div className="flex justify-end gap-3 pt-2">
          <Button type="secondary" disabled={isSubmitting} onClick={handleClose}>
            Abbrechen
          </Button>

          <Button
            type="primary"
            disabled={isSubmitting || !isValid}
            onClick={() => handleFormSubmit()}
          >
            {isSubmitting && <span className="inline-block animate-spin mr-2">⟳</span>}
            Fahrzeug erstellen
          </Button>
        </div>
      </div>
    </Dialog>
  );
}

// apps/inventar/src/lib/inventar/AddVehicleDialog.svelte
<script lang="ts">
	import { Button } from '@thw-tools/svelte-components';
	import type { CreateVehicleDto } from '$lib/api/vehicleModels';
	import { inventory } from '$lib/shared/stores/inventoryStore';

	const props = $props<{
		isOpen?: boolean;
		isSubmitting?: boolean;
		errorMessage?: string;
		onClose?: () => void;
		onSubmit?: (data: CreateVehicleDto) => void;
		onError?: (message: string) => void;
	}>();

	// Form data
	let licensePlate = $state('');
	let vehicleType = $state('');
	let radioCallName = $state('');
	let unit = $state('');
	let name = $state('');

	// Common THW vehicle types
	const vehicleTypes = ['MTW', 'MzKw', 'GKW', 'MLW', 'Kipper', 'Anhänger', 'Sonstige'];

	// Default einheiten as fallback
	const defaultEinheiten = ['Sonstige'];

	// Close the dialog
	function close() {
		if (props.onClose) props.onClose();
	}

	// Reset the form
	function resetForm() {
		licensePlate = '';
		vehicleType = '';
		radioCallName = '';
		unit = '';
		name = '';
	}

	// Create a new vehicle
	function submitForm() {
		if (!licensePlate || !vehicleType || !radioCallName || !unit || !name) {
			if (props.onError) props.onError('Bitte fülle alle Pflichtfelder aus.');
			return;
		}

		const vehicleData: CreateVehicleDto = {
			name,
			licensePlate,
			vehicleType,
			radioCallName,
			unit
		};

		if (props.onSubmit) props.onSubmit(vehicleData);
	}

	// When dialog closes, reset the form
	$effect(() => {
		if (!props.isOpen) {
			resetForm();
		}
	});

	// Get unique einheiten from inventory items
	function getUniqueEinheiten() {
		if (!$inventory.inventoryItems) return defaultEinheiten;

		// Extract all unique einheiten from inventory items
		const uniqueEinheiten = [
			...defaultEinheiten,
			...new Set($inventory.inventoryItems.map((item) => item.einheit))
		];

		// Sort alphabetically
		return uniqueEinheiten.sort();
	}
</script>

{#if props.isOpen}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg p-6 w-full max-w-lg mx-4">
			<h2 class="text-xl font-bold text-thw-700 mb-4">Neues Fahrzeug hinzufügen</h2>

			<form on:submit|preventDefault={submitForm} class="space-y-4">
				<div>
					<label for="name" class="block text-sm font-medium text-gray-700 mb-1"> Name* </label>
					<input
						id="name"
						type="text"
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
						bind:value={name}
						placeholder="z.B. MTW OV Stab"
						required
					/>
				</div>

				<div>
					<label for="licensePlate" class="block text-sm font-medium text-gray-700 mb-1">
						Kennzeichen*
					</label>
					<input
						id="licensePlate"
						type="text"
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
						bind:value={licensePlate}
						placeholder="z.B. THW-12345"
						required
					/>
				</div>

				<div>
					<label for="vehicleType" class="block text-sm font-medium text-gray-700 mb-1">
						Fahrzeugtyp*
					</label>
					<select
						id="vehicleType"
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
						bind:value={vehicleType}
						required
					>
						<option value="" disabled selected>Bitte auswählen</option>
						{#each vehicleTypes as type}
							<option value={type}>{type}</option>
						{/each}
					</select>
				</div>

				<div>
					<label for="radioCallName" class="block text-sm font-medium text-gray-700 mb-1">
						Funkrufname*
					</label>
					<input
						id="radioCallName"
						type="text"
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
						bind:value={radioCallName}
						placeholder="z.B. Heros 86/25"
						required
					/>
				</div>

				<div>
					<label for="unit" class="block text-sm font-medium text-gray-700 mb-1">
						Einheit/Bereich*
					</label>
					<select
						id="unit"
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-thw-500"
						bind:value={unit}
						required
					>
						<option value="" disabled selected>Bitte auswählen</option>
						{#each getUniqueEinheiten() as einheit}
							<option value={einheit}>{einheit}</option>
						{/each}
					</select>
				</div>

				{#if props.errorMessage}
					<div class="bg-red-50 border border-red-300 text-red-700 px-4 py-3 rounded-md">
						{props.errorMessage}
					</div>
				{/if}

				<div class="flex justify-end gap-3 pt-2">
					<Button secondary={true} disabled={props.isSubmitting} click={close}>Abbrechen</Button>

					<Button secondary={false} disabled={props.isSubmitting} click={submitForm}>
						{#if props.isSubmitting}
							<span class="inline-block animate-spin mr-2">⟳</span>
						{/if}
						Fahrzeug erstellen
					</Button>
				</div>
			</form>
		</div>
	</div>
{/if}
