// apps/inventar-next/src/components/dialog/FeedbackDialog.tsx
import { Button, Dialog } from '../base';

interface Props {
  onClose: () => void;
}

export default function FeedbackDialog({ onClose }: Props) {
  return (
    <Dialog title="Feedback">
      <div slot="content">
        <div className="flex flex-col gap-2">
          <div>Du hast Ideen für neue Tools, weitere Quizfragen oder Feedback?</div>
          <div>
            <span>Schreib mir gerne eine Direktnachricht in </span>
            <a
              data-umami-event="Feedback Dialog Hermine link"
              href="https://app.thw-messenger.de/thw/app#/contacts/profile/1990855"
              target="_blank"
              className="underline text-thw"
            >
              <span>Hermine</span>
            </a>
            <span> (Malte Sehmer).</span>
          </div>
        </div>
      </div>
      <div slot="footer">
        <Button onClick={onClose}>
          <span>Schließen</span>
        </Button>
      </div>
    </Dialog>
  );
}

// packages/svelte-components/src/components/FeedbackDialog.svelte
<script lang="ts">
	import { Dialog, Button } from '@thw-tools/svelte-components';

	interface Props {
		onClose: () => void;
	}

	let { onClose }: Props = $props();
</script>

<Dialog title="Feedback">
	{#snippet content()}
		<div>
			<div class="flex flex-col gap-2">
				<div>Du hast Ideen für neue Tools, weitere Quizfragen oder Feedback?</div>
				<div>
					Schreib mir gerne eine Direktnachricht in
					<a
						data-umami-event="Feedback Dialog Hermine link"
						href="https://app.thw-messenger.de/thw/app#/contacts/profile/1990855"
						target="_blank"
						class="underline text-thw">Hermine</a
					> (Malte Sehmer).
				</div>
			</div>
		</div>
	{/snippet}
	{#snippet footer()}
		<div>
			<Button click={onClose}>Schließen</Button>
		</div>
	{/snippet}
</Dialog>
